apiVersion: v1
kind: Pod
metadata:
  name: ethercalc
  labels:
    app: ethercalc
spec:
  containers:
    - name: ethercalc
      image: audreyt/ethercalc
      ports:
        - containerPort: 8000
      envFrom:
        - configMapRef:
            name: ethercalc-config
#      volumeMounts:
#        - name: config-volume
#          mountPath: /app/config.json
#          subPath: config.json
#      livenessProbe:
#        httpGet:
#          path: /
#          port: 80
    - name: redis
      image: redis
      command:
        - "redis-server"
        - "--appendonly"
        - "yes"
      ports:
        - containerPort: 6379
    - name: sh
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "--"
      args:
        - "while true; do sleep 30; done;"
#  volumes:
#    - name: config-volume
#      configMap:
#        name: riotwebconfig
  restartPolicy: Always

